/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "../src/Check.h"
#include "../src/DataStructure.h"
#include "../src/NextGenre.h"
#include <stdlib.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_Checkup(void);
extern void test_Checkdown(void);
extern void test_Checkleft(void);
extern void test_Checkright(void);
extern void test_Checkupleft(void);
extern void test_Checkupright(void);
extern void test_Checkdownleft(void);
extern void test_Checkdownright(void);
extern void test_evolution(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}
/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, int line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {

            setUp();
            func();

    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}


/*=======MAIN=====*/
int main(void)
{
  UnityBegin("TestCheck.c");
  run_test(test_Checkup, "test_Checkup", 33);
  run_test(test_Checkdown, "test_Checkdown", 39);
  run_test(test_Checkleft, "test_Checkleft", 45);
  run_test(test_Checkright, "test_Checkright", 51);
  run_test(test_Checkupleft, "test_Checkupleft", 57);
  run_test(test_Checkupright, "test_Checkupright", 63);
  run_test(test_Checkdownleft, "test_Checkdownleft", 69);
  run_test(test_Checkdownright, "test_Checkdownright", 75);
  run_test(test_evolution, "test_evolution", 82);

  return UnityEnd();
}
